[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
rust_decimal = "1.25"
rust_decimal_macros = "1.25"

[dev-dependencies]
regex = "0.1.41"
