[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



=======
num-traits = "0.2.15"

[dev-dependencies]
regex = "0.1.41"
>>>>>>> e3d0ab3b1fdd74e3e5c2c7075758d54501cd700c
